theme: minimal-mistakes-jekyll
plugins:
  - jekyll-include-cache
title: The JCU MVP Club
description: Software development and Entrepreneurship
collections:
  mvp_collection:
    output: true
    permalink: /:collection/:name
  posts:
    output: true
  projects_collection:
    output: true
    permalink: /:collection/:name
  posts:
    output: true
defaults:
  # _posts
  - scope:
      path: "" # an empty string here means all files in the project
      type: mvp_collection
      #type: posts
    values:
      layout: "default"
      read_time: true
      comments: true
      share: true
      related: true

