theme: jekyll-theme-hacker
title: The JCU MVP Club
description: Software development and Entrepreneurship
collections:
  mvp_collection:
    output: true
    permalink: /:collection/:name
defaults:
    scope:
      path: "" # an empty string here means all files in the project
      type: mvp_collection
    values:
      layout: "default"
